### ISSUE TITLE
minor formatting issue in print method

### ISSUE THREAD

**Issue by japhir** [pasturm/bfsl#1]
Hey! Great package!

when I print a fit in [emacs ess](ess.r-project.org/) I get a minor issue, however, probably because you used cat without a "\n" at the end :)

basically this puts the goodness of fit value before the cursor >

```
> york
Best-fit straight line

           Estimate   Std. Error
Intercept  0.1564666  0.0012860 
Slope      0.0388136  0.0001555 

Goodness of fit:
1.186> 
```

**Comment by pasturm** [comment]
Thanks for reporting. This should be fixed now.

**Comment by japhir** [comment]
Yeah, I guess there's no need to test this since it's such a simple bug. I'll close it :). Cheers!
