### ISSUE TITLE
feature request: add .predict function for class bfsl 

### ISSUE THREAD

**Issue by japhir** [pasturm/bfsl#2]
to add confidence/prediction intervals around a line, it would be great to use the [predict function](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/predict.lm.html)

```R
predict(york, newdata = 1:10, interval = "confidence", level = 0.95)
#>Error in UseMethod("predict") : 
#>  no applicable method for 'predict' applied to an object of class "bfsl"
```

[this page](https://janhove.github.io/visualise_uncertainty/) explains nicely how they use the predict function to visualize uncertainty from different kinds of models.

**Comment by japhir** [comment]
see also https://github.com/tidymodels/broom/issues/1008 :)

**Comment by pasturm** [comment]
Thanks for the suggestion. I will look into that.
I am not quite sure yet, how to implement confidence and prediction intervals in a statistically correct way in case of errors in both coordinates. But visualizing the uncertainty would definitely be nice.

**Comment by japhir** [comment]
Yeah I have no idea about the correct statistical implementation either.

- here's an [unanswered stackoverflow](https://stats.stackexchange.com/questions/472585/confidence-bands-for-model-ii-york-regression-method) question about it
- here's a [researchgate thread about the general problem](https://www.researchgate.net/post/How-can-estimate-the-prediction-interval-around-the-regression-line) with many sources in it. I haven't found anything specifically about the York regression
- In York 1968's appendix (https://dx.doi.org/10.1016/S0012-821X(68)80059-7) they describe that the error on the slope is calculated in the "usual way" and show how.

**Comment by pasturm** [comment]
I have added a predict method, which allows to calculate predictions and confidence intervals.
It does also work with geom_smooth() of ggplot2 (see [README](https://github.com/pasturm/bfsl/blob/master/README.md))

**Comment by japhir** [comment]
This works like a charm! Only current limitation I see is that you cannot specify columns of the data for `sd_x` and `sd_y` in the `method.args` list. I had an example where I add a `data = d %>% filter(X <= 150)` and this results in an error because the original `d` has not been changed, so the `sd_x` and `sd_y` are of the wrong length.

However, I guess most people will always want to compute it by hand as well, and in this case there was a quick workaround of simply saving the intermediate df.

**Comment by japhir** [comment]
I haven't actually checked the maths, by the way. Only that it produces nice whiskers on my figure ;-).

**Comment by pasturm** [comment]
I am quite confident that the math is fine. The standard errors of the fit are calculated according to York and based on these errors the confidence intervals for the conditional expectation E(y|x) where x is the future observable independent variable are calculated (as in `lm` models).

I have also updated `bfsl.formula()`, so that if `sd_x` and `sd_y` are present in the data.frame you don't have to specifiy it in `method.args` of `geom_smooth()`. I am not very familiar with the tidyverse, but maybe this solves the issue with the filtered data.

**Comment by pasturm** [comment]
Actually, I was wrong and it is not as simple. It is still necessary to explicitly specify `sd_x` and `sd_y` as `method.args` in `geom_smooth()`. I currently don't see how this could be avoided. So I guess I will leave it at that for now...
